name: python test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIB_INPUT: 10
  steps:
    - uses: actions/checkout@v2
    - name: run python
      run: python3 test.py



  test:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/checkout@v3
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
