name: python test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIB_INPUT: 10
  steps:
    - uses: actions/checkout@v2
    - name: run python
      run: python3 test.py
